---
postgres_user: "{{ lookup('env', 'POSTGRES_USER') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
postgres_db: keycloak
postgres_container_name: "{{ lookup('env', 'POSTGRES_CONTAINER_NAME') }}"
keycloak_admin_user: "{{ lookup('env', 'KEYCLOAK_ADMIN_USER') }}"
keycloak_admin_password: "{{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD') }}"
keycloak_container_name: "{{ lookup('env', 'KEYCLOAK_CONTAINER_NAME') }}"
web_container_name: webserver
