---
- name: Deploy and configure web server with Keycloak authentication
  hosts: keycloak_server
  become: true
  tasks:
    - name: Pull NGINX image
      docker_image:
        name: nginx
        source: pull
    
    - name: Start web server container
      docker_container:
        name: "{{ web_container_name }}"
        image: nginx
        ports:
          - "80:80"
        state: started
        restart_policy: always
    
    - name: Copy NGINX configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart NGINX
  
  handlers:
    - name: Restart NGINX
      docker_container:
        name: "{{ web_container_name }}"
        state: restarted