- name: Configure Keycloak
  hosts: azure_vm
  vars:
    keycloak_url: "http://localhost:8080/auth"
    keycloak_user: "admin"
    keycloak_password: "admin_password"
    realm_name: "webserver-access"
    realm_id: "webserver-access"
    client_id: "nginx-webserver"
    client_secret: "replace-with-generated-secret"
    user_username: "john_doe"
    user_password: "password123"
    user_email: "john@example.com"
    user_first_name: "John"
    user_last_name: "Doe"
    user_roles:
      - "web-user"

  tasks:
    - name: Create a new realm
      community.general.keycloak_realm:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_username: "{{ keycloak_user }}"
        auth_password: "{{ keycloak_password }}"
        auth_realm: "master"
        id: "{{ realm_id }}"
        realm: "{{ realm_name }}"
        enabled: true
        state: present

    - name: Add a new client
      community.general.keycloak_client:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_username: "{{ keycloak_user }}"
        auth_password: "{{ keycloak_password }}"
        auth_realm: "master"
        realm: "{{ realm_name }}"
        client_id: "{{ client_id }}"
        secret: "{{ client_secret }}"
        standard_flow_enabled: true
        direct_access_grants_enabled: false
        implicit_flow_enabled: false
        service_accounts_enabled: false
        public_client: false  # Corresponds to "confidential" access type
        redirect_uris:
          - "http://52.165.45.10//*"
          - "https://52.165.45.10//*"
        web_origins:
          - "*"
        state: present

    - name: Create roles
      community.general.keycloak_role:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_username: "{{ keycloak_user }}"
        auth_password: "{{ keycloak_password }}"
        auth_realm: "master"
        realm: "{{ realm_name }}"
        name: "{{ item }}"
        client_id: "{{ client_id }}"
        state: present
      loop:
        - "web-user"
        - "admin"

    - name: Add a user
      community.general.keycloak_user:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_username: "{{ keycloak_user }}"
        auth_password: "{{ keycloak_password }}"
        auth_realm: "master"
        realm: "{{ realm_name }}"
        username: "{{ user_username }}"
        password: "{{ user_password }}"
        enabled: true
        email: "{{ user_email }}"
        first_name: "{{ user_first_name }}"
        last_name: "{{ user_last_name }}"
        state: present

    - name: Assign roles to the user
      community.general.keycloak_client_rolemapping:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_username: "{{ keycloak_user }}"
        auth_password: "{{ keycloak_password }}"
        auth_realm: "master"
        realm: "{{ realm_name }}"
        client_id: "{{ client_id }}"
        user: "{{ user_username }}"
        roles:
          - name: "{{ item }}"
        state: present
      loop: "{{ user_roles }}"
