- name: Configure Keycloak
  hosts: azure_vm
  become: yes
  vars:
    keycloak_url: "http://localhost:8080"
    auth_realm: "master"
    auth_username: "admin"
    auth_password: "admin_password"
    realm_name: "webserver-access"
    realm_display_name: "Web Server Access Realm"
    realm_id: "webserver-access-id"
    client_id: "nginx-webserver"
    client_secret: "replace-with-generated-secret"

  tasks:
    - name: Create a new realm
      community.general.keycloak_realm:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: "{{ auth_realm }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        realm: "{{ realm_name }}"
        id: "{{ realm_id }}"
        display_name: "{{ realm_display_name }}"
        enabled: true
        state: present

    - name: Add a new client
      community.general.keycloak_client:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: "{{ auth_realm }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        realm: "{{ realm_name }}"
        client_id: "{{ client_id }}"
        secret: "{{ client_secret }}"
        standard_flow_enabled: true
        redirect_uris:
          - "http://52.165.45.10/*" 
        web_origins:
          - "*"
        public_client: false
        state: present

    - name: Create roles
      community.general.keycloak_role:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: "{{ auth_realm }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        realm: "{{ realm_name }}"
        name: "{{ item }}"
        client_id: "{{ client_id }}"
        state: present
      loop:
        - web-user
        - admin

    - name: Add a user
      community.general.keycloak_user:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: "{{ auth_realm }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        realm: "{{ realm_name }}"
        username: "john_doe"
        password: "password123"
        enabled: true
        email: "john@example.com"
        first_name: "John"
        last_name: "Doe"
        state: present

    - name: Assign roles to the user
      community.general.keycloak_client_rolemapping:
        auth_keycloak_url: "{{ keycloak_url }}"
        auth_realm: "{{ auth_realm }}"
        auth_username: "{{ auth_username }}"
        auth_password: "{{ auth_password }}"
        realm: "{{ realm_name }}"
        client_id: "{{ client_id }}"
        user: "john_doe"
        roles:
          - name: "web-user"
        state: present
