- name: Deploy Postgres Container
  hosts: azure_vm
  become: yes
  tasks:
    - name: Pull Postgres image
      docker_image:
        name: postgres:latest
        source: pull

    - name: Run Postgres container
      docker_container:
        name: postgres_db
        image: postgres:latest
        env:
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: keycloak_password
          POSTGRES_DB: keycloak_db
        ports:
          - "5432:5432"
        volumes:
          - postgres_data:/var/lib/postgresql/data
        restart_policy: always
  vars:
    ansible_python_interpreter: /usr/bin/python3
