- name: Deploy Keycloak Container
  hosts: azure_vm
  become: yes
  vars:
    keycloak_image: quay.io/keycloak/keycloak:latest
    keycloak_ports:
      - "8080:8080"
      - "8443:8443"
    postgres_ip: "172.17.0.1"  # Update this to the actual IP of your PostgreSQL container or service if it's different
    keycloak_db_name: "keycloak_db"
    keycloak_db_user: "keycloak"
    keycloak_db_password: "keycloak_password"
    keycloak_admin_user: "admin"
    keycloak_admin_password: "admin_password"

  tasks:
    # Pull the latest Keycloak Docker image
    - name: Pull Keycloak image
      docker_image:
        name: "{{ keycloak_image }}"
        source: pull

    # Run the Keycloak container with the updated startup command
    - name: Run Keycloak container
      docker_container:
        name: keycloak_server
        image: "{{ keycloak_image }}"
        command: "start-dev --http-enabled=true --http-port=8080 --hostname-strict=false"
        env:
          KC_DB: postgres
          KC_DB_URL: "jdbc:postgresql://{{ postgres_ip }}/{{ keycloak_db_name }}"
          KC_DB_USERNAME: "{{ keycloak_db_user }}"
          KC_DB_PASSWORD: "{{ keycloak_db_password }}"
          KC_ADMIN: "{{ keycloak_admin_user }}"
          KC_ADMIN_PASSWORD: "{{ keycloak_admin_password }}"
        ports: "{{ keycloak_ports }}"
        restart_policy: always

    # Wait for the Keycloak container to be ready
    - name: Wait for Keycloak to start
      wait_for:
        host: localhost
        port: 8080
        delay: 10
        timeout: 120
        state: started
