- name: Deploy Keycloak Container
  hosts: azure_vm
  become: yes
  vars:
    keycloak_image: quay.io/keycloak/keycloak:latest
    keycloak_ports:
      - "8080:8080"
      - "8443:8443"
    keycloak_ssl_host_directory: /opt/keycloak/ssl
    keycloak_ssl_container_directory: /opt/keycloak/ssl
    keycloak_cert_file: keycloak.crt
    keycloak_key_file: keycloak.key
    keycloak_keystore_password: secret
    postgres_ip: 172.17.0.1
    keycloak_db_name: keycloak_db
    keycloak_db_user: keycloak
    keycloak_db_password: keycloak_password
    keycloak_admin_user: admin
    keycloak_admin_password: Admin_password12!
  tasks:
    # Ensure SSL directory exists on the host
    - name: Ensure directory for SSL keystore exists on the host
      ansible.builtin.file:
        path: "{{ keycloak_ssl_host_directory }}"
        state: directory
        owner: 1000
        group: 1000
        mode: '0755'

    # Copy SSL certificate to the host
    - name: Copy the Keycloak SSL certificate to the host
      ansible.builtin.copy:
        src: ./{{ keycloak_cert_file }}
        dest: "{{ keycloak_ssl_host_directory }}/{{ keycloak_cert_file }}"
        owner: 1000
        group: 1000
        mode: '0644'

    # Copy SSL key to the host
    - name: Copy the Keycloak SSL key to the host
      ansible.builtin.copy:
        src: ./{{ keycloak_key_file }}
        dest: "{{ keycloak_ssl_host_directory }}/{{ keycloak_key_file }}"
        owner: 1000
        group: 1000
        mode: '0600'

    # Run the Keycloak container
    - name: Run Keycloak container
      docker_container:
        name: keycloak_server
        image: "{{ keycloak_image }}"
        command: "start --https-port=8443 --http-port=8080 --hostname-strict=false --verbose"
        env:
          KC_DB: postgres
          KC_DB_URL: "jdbc:postgresql://{{ postgres_ip }}/{{ keycloak_db_name }}"
          KC_DB_USERNAME: "{{ keycloak_db_user }}"
          KC_DB_PASSWORD: "{{ keycloak_db_password }}"
          KC_HTTPS_CERTIFICATE_FILE: "{{ keycloak_ssl_container_directory }}/{{ keycloak_cert_file }}"
          KC_HTTPS_CERTIFICATE_KEY_FILE: "{{ keycloak_ssl_container_directory }}/{{ keycloak_key_file }}"
          KEYCLOAK_ADMIN: "{{ keycloak_admin_user }}"
          KEYCLOAK_ADMIN_PASSWORD: "{{ keycloak_admin_password }}"
        ports: "{{ keycloak_ports }}"
        volumes:
          - "{{ keycloak_ssl_host_directory }}:{{ keycloak_ssl_container_directory }}"
        restart_policy: always

    # Wait for Keycloak to start
    - name: Wait for Keycloak to start
      wait_for:
        host: localhost
        port: 8443
        delay: 10
        timeout: 120
        state: started
